# Numpy_Assignment_2::

In [2]:
import numpy as np

## Question:1

#### Convert a 1D array to a 2D array with 2 rows?

In [4]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x=np.reshape(x,(2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

#### How to stack two arrays vertically?

In [79]:
x1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
x2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19]).reshape(2,5)
x2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
arr=np.vstack((x1,x2))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
arrS= arr[2] 
arrS [:] = 1
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 1,  1,  1,  1,  1],
       [15, 16, 17, 18, 19]])

In [26]:
arrS= arr[3] 
arrS [:] = 1
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

#### How to stack two arrays horizontally?

In [27]:
x1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
x2=np.array([1,1, 1, 1, 1, 1, 1, 1, 1, 1]).reshape(2,5)
x2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.hstack((x1,x2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

#### How to convert an array of arrays into a flat 1d array?

In [31]:
x1=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
x1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

#### How to Convert higher dimension into one dimension?

In [36]:
x1=np.array([[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9],[10,11,12,13,14]]])
x1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [38]:
arr = np.ravel(x1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6


#### Convert one dimension to higher dimension?

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:7


#### Create 5x5 an array and find the square of an array?

In [50]:
x = np.random.random((5,5))
x

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

In [51]:
np.square(x)

array([[0.04928097, 0.75817475, 0.04273281, 0.843846  , 0.23854549],
       [0.37423055, 0.58661484, 0.26875721, 0.08809054, 0.03523926],
       [0.00651915, 0.54529407, 0.19475383, 0.02506201, 0.77428918],
       [0.07512339, 0.17159065, 0.08766333, 0.39537423, 0.33621189],
       [0.35991504, 0.0706598 , 0.08104605, 0.06430698, 0.10729814]])

## Question:8


#### Create 5x6 an array and find the mean?

In [55]:
y = np.random.randn(5,6)
y

array([[ 2.66504906, -0.21017082, -0.73668102, -0.28415804,  0.21319905,
        -2.4005372 ],
       [-0.11209336,  0.40226978, -0.05558717, -0.99798236,  0.05019618,
         1.19200034],
       [ 1.3835964 , -0.24585362,  0.052122  , -0.34423888,  0.23084314,
        -0.04216643],
       [-0.20786334, -1.35218081, -1.02077299,  1.2334356 ,  0.65340573,
        -0.21706802],
       [-0.11069605,  0.5439582 , -0.29673933,  0.69675408,  0.05404728,
        -0.84408314]])

In [57]:
np.mean(y)

-0.0035998578313096237

## Question:9


#### Find the standard deviation of the previous array in Q8?

In [58]:
np.std(y)

0.9097930773826082

## Question:10


#### Find the median of the previous array in Q8?

In [59]:
np.median(y)

-0.0831416081999427

## Question:11


#### Find the transpose of the previous array in Q8?

In [60]:
np.transpose(y)

array([[ 2.66504906, -0.11209336,  1.3835964 , -0.20786334, -0.11069605],
       [-0.21017082,  0.40226978, -0.24585362, -1.35218081,  0.5439582 ],
       [-0.73668102, -0.05558717,  0.052122  , -1.02077299, -0.29673933],
       [-0.28415804, -0.99798236, -0.34423888,  1.2334356 ,  0.69675408],
       [ 0.21319905,  0.05019618,  0.23084314,  0.65340573,  0.05404728],
       [-2.4005372 ,  1.19200034, -0.04216643, -0.21706802, -0.84408314]])

## Question:12

#### Create a 4x4 an array and find the sum of diagonal elements?

In [61]:
z = np.random.random((4,4))
z

array([[0.66084439, 0.89298429, 0.96515755, 0.76993268],
       [0.75909912, 0.71004905, 0.70155283, 0.76733138],
       [0.97434948, 0.37371452, 0.08305444, 0.23964044],
       [0.22148276, 0.3635998 , 0.81031423, 0.06009617]])

In [65]:
np.diagonal(z)

array([0.66084439, 0.71004905, 0.08305444, 0.06009617])

In [66]:
np.diagonal(z).sum()

1.5140440512176185

## Question:13

#### Find the determinant of the previous array in Q12?

In [69]:
np.linalg.det(z)

-0.051742537624843404

## Question:14

#### Find the 5th and 95th percentile of an array?


In [71]:
a = np.random.random((3,3))
a

array([[0.81464201, 0.81028553, 0.58937388],
       [0.91473434, 0.05982164, 0.96499664],
       [0.57097522, 0.30251811, 0.82570583]])

In [76]:
print("5th percentile of an array: ",np.percentile(a, 5))

5th percentile of an array:  0.15690022705293846


In [75]:
print("95th percentile of an array: ",np.percentile(a, 95))

95th percentile of an array:  0.9448917202091842


## Question:15

#### How to find if a given array has any null values?

In [3]:
arr = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, np.NaN, 13, 14],
       [15, 16, 17, 18, 19]])
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., nan, 13., 14.],
       [15., 16., 17., 18., 19.]])

In [4]:
array_sum = np.sum(arr)
array_has_nan = np.isnan(array_sum)
array_has_nan

True