## Difficulty Level Beginner

 #### 1. Import the numpy package under the name np

In [1]:
import numpy as np

 #### 2. Create a null vector of size 10

In [2]:
np.zeros(10) #considering zeros as null values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr1 =  np.empty(10)
arr1 [:] = np.NaN #considering not a number as a null value
arr1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

 #### 3. Create a vector with values ranging from 10 to 49

In [6]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

 #### 4. Find the shape of previous array in question 3

In [7]:
np.shape(x)

(40,)

 #### 5. Print the type of the previous array in question 3

In [8]:
type(x) #type of array

numpy.ndarray

In [11]:
x.dtype

dtype('int64')

 #### 6. Print the numpy version and the configuration

In [3]:
np.__version__

'1.18.1'

In [4]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/namrah/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/namrah/anaconda3/include']


 #### 7. Print the dimension of the array in question 3

In [17]:
x.ndim

1

 #### 8. Create a boolean array with all the True values

In [6]:
bool_arr = np.ones(10, dtype=bool) #Method: 1
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
bools = np.array([True, True, True, True]) #Method: 2
bools.all() 

True

 #### 9. Create a two dimensional array

In [6]:
x=np.random.randn(2,2)
x

array([[-0.79343239, -0.17495038],
       [-1.23573122, -1.30027785]])

 #### 10. Create a three dimensional array

In [7]:
x=np.random.randn(3,3,3)
x

array([[[-0.22291703, -0.80313257, -2.6034858 ],
        [ 0.50465646,  1.14996723, -1.01252669],
        [-1.35155168,  0.80982936,  0.99777587]],

       [[ 0.54665466,  0.50402906, -0.29319248],
        [-0.00528672, -0.06396903,  0.48500218],
        [ 0.72166579, -1.01318113, -0.74145157]],

       [[ 1.61369661,  0.28215624,  0.01476013],
        [ 2.4800004 , -1.30417187, -0.64870403],
        [-1.01877339, -0.22856882, -1.22334437]]])

## Difficulty Level Easy

 #### 1. Reverse a vector (first element becomes last)

In [30]:
y = np.arange(12, 38)
y

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [35]:
y = y[::-1]
y

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

 #### 2. Create a null vector of size 10 but the fifth value which is 1

In [10]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

3. Create a 3x3 identity matrix

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. arr = np.array([1, 2, 3, 4, 5])
    #### Convert the data type of the given array from int to float

In [41]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [42]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

5. (a) arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

   (b) arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
           
#### Multiply arr1 with arr2

In [46]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [48]:
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

6. (a) arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

   (b)arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
#### Make an array by comparing both the arrays provided above

In [24]:
arr1 = np.array([[1., 2., 3.],

     [4., 5., 6.]]) 
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr2 = np.array([[0., 4., 1.],

     [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [55]:
arr3 = arr1 == arr2
arr3

array([[False, False, False],
       [False, False, False]])

 #### 7. Extract all odd numbers from arr with values(0-9)

In [11]:
odd = np.array([0,1,2,3,4,5,6,7,8,9])
odd[odd % 2 == 1]

array([1, 3, 5, 7, 9])

 #### 8. Replace all odd numbers to -1 from previous array

In [12]:
odd = np.array([0,1,2,3,4,5,6,7,8,9])
np.where( odd%2 == 1, -1, odd )

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

9. arr = np.arange(10)
#### Replace the values of indexes 5,6,7 and 8 to 12

In [128]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

 #### 10. Create a 2d array with 1 on the border and 0 inside

In [14]:
x = np.ones((6,6))
x [1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Difficulty Level Medium

1. arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
#### Replace the value 5 to 12

In [165]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
arr2d [arr2d == 5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [186]:
arr2d [1]

array([ 4, 12,  6])

2. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#### Convert all the values of 1st array to 64

In [8]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0][0:1]=64 #Method:1
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [264]:
arrS= arr3d[0] #Method:2
arrS [:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
old_values = arr3d[0].copy() #Method:3
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

  #### 3. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [14]:
array1 = np.array([0,1,2,3,4,5,6,7,8,9])
array1 = array1.reshape(2,-1)
array1


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
array1[0]

array([0, 1, 2, 3, 4])

  #### 4. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [18]:
array2 = np.array([0,1,2,3,4,5,6,7,8,9])
array2 = array1.reshape(2,-1)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
array2[1][1] #slicing out 2nd value from 2nd 1-D array

6

#### 5. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [16]:
array3 = np.array([0,1,2,3,4,5,6,7,8,9])
array3 = array1.reshape(2,-1)
array3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
array3[:,2] #Method:1

array([2, 7])

In [27]:
array3[0:, 2:3] ##Method:2

array([[2],
       [7]])

 #### 6. Create a 10x10 array with random values and find the minimum and maximum values

In [300]:
ran = np.random.random((10,10))
ran

array([[0.85383317, 0.68460771, 0.5908744 , 0.83825312, 0.21226341,
        0.79899551, 0.99756962, 0.48701544, 0.49214036, 0.46693219],
       [0.50300065, 0.96246391, 0.50729828, 0.72016524, 0.51734283,
        0.67398523, 0.45202464, 0.54917625, 0.16252037, 0.28669988],
       [0.90319382, 0.84255048, 0.75429355, 0.03193889, 0.95113501,
        0.0896452 , 0.85755   , 0.49726782, 0.26427333, 0.87514546],
       [0.57605906, 0.66258854, 0.00117454, 0.0460897 , 0.94545497,
        0.54302354, 0.21849434, 0.2375403 , 0.0573708 , 0.9305872 ],
       [0.76059466, 0.77926845, 0.54255399, 0.81552206, 0.76839273,
        0.6785042 , 0.42040577, 0.29842039, 0.72897155, 0.50434278],
       [0.74328638, 0.191973  , 0.68107785, 0.25241932, 0.76688906,
        0.10645565, 0.07694838, 0.89988847, 0.08588499, 0.9484777 ],
       [0.67962903, 0.36051724, 0.18565482, 0.94007349, 0.52118295,
        0.0999531 , 0.70145459, 0.92934707, 0.56049974, 0.31341675],
       [0.41526142, 0.78086419, 0.7438909

In [301]:
ran.min()

0.001174543446178622

In [302]:
ran.max()

0.9975696182335387

7. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#### Find the common items between a and b

In [307]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [305]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [306]:
np.intersect1d (a, b)

array([2, 4])

8. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
#### Find the positions where elements of a and b match

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [19]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [50]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [20]:
np.where(np.in1d(a,b) == True)

(array([1, 3, 5, 7]),)

9. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
#### Find all the values from array data where the values from array names are not equal to Will

In [333]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

In [336]:
data = np.random.randn(7, 4)
data

array([[ 1.48758905e+00, -1.48030658e+00,  4.67037653e-01,
         4.87916439e-01],
       [-8.20079651e-01, -3.34564071e+00,  1.37434838e+00,
        -4.05842702e-01],
       [ 5.95662580e-01, -1.65680659e+00,  2.74786692e-03,
         5.22602540e-01],
       [ 2.94823442e-01, -1.29335334e+00,  8.36373139e-02,
        -9.18569562e-01],
       [ 5.98596972e-01,  2.02422277e-01, -1.06460716e+00,
         2.13150174e+00],
       [-4.05901849e-01, -8.38258263e-01,  9.24780330e-01,
        -5.14135735e-02],
       [ 3.37707067e-01, -2.12968205e+00,  2.10894908e+00,
        -1.57342050e+00]])

In [337]:
data[names != 'Will']

array([[ 1.48758905, -1.48030658,  0.46703765,  0.48791644],
       [-0.82007965, -3.34564071,  1.37434838, -0.4058427 ],
       [ 0.29482344, -1.29335334,  0.08363731, -0.91856956],
       [-0.40590185, -0.83825826,  0.92478033, -0.05141357],
       [ 0.33770707, -2.12968205,  2.10894908, -1.5734205 ]])

10.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
#### Find all the values from array data where the values from array names are not equal to Will and Joe

In [21]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = (names != 'Joe') & (names != 'Will')
names

array([ True, False, False,  True, False, False, False])

In [22]:
data = np.random.randn(7, 4)
data[names]

array([[ 0.39542592,  1.31683448, -0.39951356,  0.41032572],
       [ 0.3851259 , -1.97332208,  2.23373867,  0.79200165]])

## Difficulty Level Hard

#### 1. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [385]:
array1 = np.arange(1,16).reshape(5,3)
array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [386]:
array1 = array1.astype('float64') 
array1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [387]:
array1.dtype

dtype('float64')

#### 2. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [383]:
array2 = np.arange(1,17).reshape(2, 2, 4)
array2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [51]:
array2 = array2.astype('float64') 
array2

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [52]:
array2.dtype

dtype('float64')

#### 3. Swap axes of the array you created in Question 32

In [23]:
arr = np.arange(1,17).reshape(2, 2, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [25]:
arr.swapaxes(1,2)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

#### 4. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [26]:
arr = np.array([10, 65, 98, 45, 2, 62, 1, 0.2, 7, 4])
arr

array([10. , 65. , 98. , 45. ,  2. , 62. ,  1. ,  0.2,  7. ,  4. ])

In [27]:
a = np.sqrt(arr)
a

array([3.16227766, 8.06225775, 9.89949494, 6.70820393, 1.41421356,
       7.87400787, 1.        , 0.4472136 , 2.64575131, 2.        ])

In [28]:
a [a < 0.5] = 0.0
a

array([3.16227766, 8.06225775, 9.89949494, 6.70820393, 1.41421356,
       7.87400787, 1.        , 0.        , 2.64575131, 2.        ])

In [29]:
np.where(np.sqrt(a) < 0.5, 0, np.sqrt(a))

array([1.77827941, 2.83941151, 3.14634628, 2.59002006, 1.18920712,
       2.80606626, 1.        , 0.        , 1.62657656, 1.41421356])

#### 5. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [30]:
a = np.random.randn(12)
a

array([ 0.90642664, -0.39936553, -1.43417303,  1.67184805,  0.12878926,
        0.39022663, -0.92483513,  0.00638356,  1.02640005,  0.45978889,
       -0.69430831, -0.04553122])

In [31]:
b = np.random.randn(12)
b

array([-0.94147401,  1.08641312, -1.47645699,  0.19520236,  0.97400409,
        0.4633127 , -0.69810323, -0.1797981 ,  0.22011387, -0.6615227 ,
       -0.68214231,  1.06723004])

In [32]:
arr=np.maximum(a,b) #Method:1
arr

array([ 0.90642664,  1.08641312, -1.43417303,  1.67184805,  0.97400409,
        0.4633127 , -0.69810323,  0.00638356,  1.02640005,  0.45978889,
       -0.68214231,  1.06723004])

In [82]:
c = a.max() #Method:2
c

1.5224551339241108

In [83]:
d = b.max()
d

1.5469545472681991

In [84]:
np.array([c,d])

array([1.52245513, 1.54695455])

6. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
#### Find the unique names and sort them out!

In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [98]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [99]:
sorted(set(names))

['Bob', 'Joe', 'Will']

7. a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
#### From array a remove all items present in array b

In [100]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [102]:
b = np.array([5,6,7,8,9])
b

array([5, 6, 7, 8, 9])

In [104]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

#### 8. Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [56]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [57]:
newColumn = np.array([[10,10,10]]).reshape(3,1)
newColumn

array([[10],
       [10],
       [10]])

In [58]:
c = np.delete(sampleArray,1,1)
c

array([[34, 73],
       [82, 12],
       [53, 66]])

In [59]:
arr = np.append(c, newColumn, axis=1)
arr

array([[34, 73, 10],
       [82, 12, 10],
       [53, 66, 10]])

In [60]:
arr[:, [0,2,1]] #Method:1

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [33]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) #Method:2
newColumn = np.array([[10,10,10]])
sampleArray[:,1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

9. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
#### Find the dot product of the above two matrix

In [120]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [121]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [122]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

#### 10. Generate a matrix of 20 random values and find its cumulative sum

In [124]:
a = np.random.randn(20)
a

array([ 0.02074747, -1.0857168 ,  0.87929696,  1.8207134 ,  2.11942993,
       -1.29023645,  1.21857663, -1.44058276,  0.0679659 ,  0.2011595 ,
       -0.48898506, -0.4562848 , -0.14475094,  0.07571396,  1.20379392,
        0.33729079, -0.24511064, -1.87007488,  0.37512709,  0.53618904])

In [128]:
np.cumsum(a)

array([ 0.02074747, -1.06496933, -0.18567236,  1.63504104,  3.75447097,
        2.46423452,  3.68281115,  2.24222839,  2.31019428,  2.51135378,
        2.02236872,  1.56608392,  1.42133298,  1.49704694,  2.70084085,
        3.03813164,  2.79302101,  0.92294613,  1.29807322,  1.83426226])